apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
data:
  application.yml: |
    micronaut:
      server:
        port: {{ .Values.deployment.containerPort }}
      application:
        name: helloMicronaut
    hello:
      greeting: {{ .Values.deployment.greeting }}
      location: {{ .Values.deployment.location }}


